### ISSUE TITLE
problem in handling erroneous data packages

### ISSUE THREAD

**Issue by svicario** [Justas1988/codec8e-parser-tcp-server#7]
Really thanks for this very nice listener and parser of teltonika codec 8 extended! Really thanks.
I did a small change but I am not sure is an improvement.  
When the client Teltonika send an invalid packet ( in my case it send sometimes a "ff" message at the end of a series of packet),  the server  stop parsing as it should but also do not read anymore new packet. 
I modified the "no expected DATA received" consequence from "break" to "conn.close()" and it recover connection after few minutes in time for next burst
Does my solution is a general improvement or have some limitations?

**Comment by Justas1988** [comment]
Hello, sorry for late reply, I was not very active on GIT lately.

Teltonika tracker sending "FF" at end of packets if not part of Teltonika DATA sending protocol:
https://wiki.teltonika-gps.com/view/Codec

I believe what happens is that Tracker is trying to keep connection open (after finishing DATA sending) and pinging with FF packets. My script does not handle this part unfortunetaly, it should actually ignore FF packets and keep connection open until its closed by the tracker. But since this is single threaded server it would then allow one device to hog the server indefinitely - so its not good.

The fact that you changed it from break to conn.close() should not make a difference in how script works. Both options would close the connection and server would start listening for socket again, until another connections session is made by the tracker. Tarcker reconnects depending on Data acquisition settings (so it can be a few minutes or seconds depending on how it is set-up).

In conclusion:

Script is single threaded and intended more as a test tool. To use it as proper server code - it would at least need to be writen to handle multithreaded connections and handle more exceptions like FF packets you mentioned (and maybe many things more which I dont even think about yet)

Script works on single connection / single DATA sending session - once tracker finishes sending DATA it waits until socket timeout is reached or socket is closed by tracker (FF packets are not handled)

"break" to "conn.close()" - should not make a difference in how script works, both would restart the socket.

More regarding the FF packets - it's not important to allow device to keep connection open in this case because we are not using Codec12 server commands here (thats the main reason why you would want constant connection to server)

If tracker has many DATA packets to send it will send them anyway one by one in single session. If tracker is pinging server with FF it means it has no packets to send immediatly.

hope this helps.

**Comment by svicario** [comment]
thanks for the feedback, I will check for the multi-thread improvement.
